// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using WebAPI_tutorial_peliculas.Context;

#nullable disable

namespace WebAPI_tutorial_peliculas.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20230909005440_migracion")]
    partial class migracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "bef4cbd4-1f2b-472f-a1e2-e1a901f6808c",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c2ee6493-5a73-46f3-a3f2-46d1d11d7176",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6a918447-ae55-41a4-bafe-8c5a66850618",
                            Email = "admin@testing.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "admin@testing.com",
                            NormalizedUserName = "admin@testing.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEOWOPHfI51qfO0s1H3hQ/tAFuG6k3Y3isnhrmTH+bZrKRkkc/MoakXiGAlbGa3AVbA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "79828cae-02bb-40c0-bcba-96fc231d3682",
                            TwoFactorEnabled = false,
                            UserName = "admin@testing.com"
                        },
                        new
                        {
                            Id = "e0765c93-676c-4199-b7ee-d7877c471821",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f26daae1-f9af-492b-8449-905012801675",
                            Email = "user@testing.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "user@testing.com",
                            NormalizedUserName = "user@testing.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEDEY/EXTYq1qfTWu6csLPdWpEg1N9a1nvgvYULFlIo25GJAEQm/+0/Hk70PVoaOe+g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6d6329d5-2d59-4599-8772-d38e4d9a46a7",
                            TwoFactorEnabled = false,
                            UserName = "user@testing.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "role",
                            ClaimValue = "admin",
                            UserId = "c2ee6493-5a73-46f3-a3f2-46d1d11d7176"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebAPI_tutorial_peliculas.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Born")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Actor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Born = new DateTime(1962, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(535),
                            Name = "Jim Carrey",
                            PhotoURL = "https://www.gettyimages.com/photos/jim-carrey",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(536)
                        },
                        new
                        {
                            Id = 2,
                            Born = new DateTime(1965, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(540),
                            Name = "Robert Downey Jr",
                            PhotoURL = "https://www.gettyimages.com/photos/robert-downey-jr",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(540)
                        },
                        new
                        {
                            Id = 3,
                            Born = new DateTime(1981, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(542),
                            Name = "Chris Evans",
                            PhotoURL = "https://www.gettyimages.com/photos/chris-evans-robert-downey-jr",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(542)
                        },
                        new
                        {
                            Id = 4,
                            Born = new DateTime(1975, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(543),
                            Name = "Angelina Jolie",
                            PhotoURL = "https://www.gettyimages.com/photos/angelina-jolie",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(544)
                        },
                        new
                        {
                            Id = 5,
                            Born = new DateTime(1967, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(545),
                            Name = "Julia Roberts",
                            PhotoURL = "https://www.gettyimages.com/photos/julia-roberts",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(545)
                        },
                        new
                        {
                            Id = 6,
                            Born = new DateTime(1990, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(546),
                            Name = "Margot Robbie",
                            PhotoURL = "https://www.gettyimages.com/photos/margot-robbie",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(547)
                        },
                        new
                        {
                            Id = 7,
                            Born = new DateTime(1963, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(548),
                            Name = "Brad Pitt",
                            PhotoURL = "https://www.gettyimages.com/photos/brad-pitt",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(564)
                        },
                        new
                        {
                            Id = 8,
                            Born = new DateTime(1974, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(582),
                            Name = "Penelope Cruz",
                            PhotoURL = "https://www.gettyimages.com/photos/penelope-cruz",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(582)
                        },
                        new
                        {
                            Id = 9,
                            Born = new DateTime(1984, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(583),
                            Name = "Scarlett Johansson",
                            PhotoURL = "https://www.gettyimages.com/photos/scarlett-johansson",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(584)
                        },
                        new
                        {
                            Id = 10,
                            Born = new DateTime(1986, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(585),
                            Name = "Megan Fox",
                            PhotoURL = "https://www.gettyimages.com/photos/megan-fox",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(587)
                        },
                        new
                        {
                            Id = 11,
                            Born = new DateTime(1975, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(588),
                            Name = "Angelina Jolie",
                            PhotoURL = "https://www.gettyimages.com/photos/angelina-jolie",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(589)
                        },
                        new
                        {
                            Id = 12,
                            Born = new DateTime(1969, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(590),
                            Name = "Jennifer Aniston",
                            PhotoURL = "https://www.gettyimages.com/photos/jennifer-aniston",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(591)
                        },
                        new
                        {
                            Id = 13,
                            Born = new DateTime(1988, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(592),
                            Name = "Emma Stone",
                            PhotoURL = "https://www.gettyimages.com/photos/emma-stone",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(593)
                        });
                });

            modelBuilder.Entity("WebAPI_tutorial_peliculas.Models.ActorMovie", b =>
                {
                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Character")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("ActorId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("ActorMovie");

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            MovieId = 1,
                            Character = "superhero",
                            Order = 1
                        },
                        new
                        {
                            ActorId = 2,
                            MovieId = 1,
                            Character = "supervillian",
                            Order = 2
                        },
                        new
                        {
                            ActorId = 3,
                            MovieId = 2,
                            Character = "main character",
                            Order = 1
                        },
                        new
                        {
                            ActorId = 4,
                            MovieId = 2,
                            Character = "supporting role",
                            Order = 2
                        },
                        new
                        {
                            ActorId = 5,
                            MovieId = 3,
                            Character = "protagonist",
                            Order = 1
                        },
                        new
                        {
                            ActorId = 1,
                            MovieId = 4,
                            Character = "antagonist",
                            Order = 2
                        },
                        new
                        {
                            ActorId = 2,
                            MovieId = 5,
                            Character = "hero",
                            Order = 1
                        },
                        new
                        {
                            ActorId = 3,
                            MovieId = 5,
                            Character = "sidekick",
                            Order = 2
                        });
                });

            modelBuilder.Entity("WebAPI_tutorial_peliculas.Models.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cinema");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(3440),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-56.13621764762051 -34.90292421243134)"),
                            Name = "Moviecenter",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(3444)
                        },
                        new
                        {
                            Id = 2,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(3482),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-56.14677015960076 -34.90889872353638)"),
                            Name = "LIFE Cinemas",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(3482)
                        },
                        new
                        {
                            Id = 3,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(3486),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-56.1566407649374 -34.91871301506793)"),
                            Name = "Casablanca",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(3487)
                        },
                        new
                        {
                            Id = 4,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(3493),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-56.2010689038137 -34.90849834167495)"),
                            Name = "Cinemateca",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(3493)
                        },
                        new
                        {
                            Id = 5,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(3496),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-56.15886454873049 -34.923823012219856)"),
                            Name = "Punta Carretas Shopping",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(3496)
                        },
                        new
                        {
                            Id = 21,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(3508),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-56.164532 -34.901112)"),
                            Name = "AMC Times Square",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(3508)
                        },
                        new
                        {
                            Id = 22,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(3511),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-56.168498 -34.914314)"),
                            Name = "Regal LA Live",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(3511)
                        },
                        new
                        {
                            Id = 23,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(3515),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-56.18133 -34.905004)"),
                            Name = "Cineplex Chicago",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(3515)
                        },
                        new
                        {
                            Id = 24,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(3517),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-56.153841 -34.920369)"),
                            Name = "AMC Miami Beach",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(3518)
                        },
                        new
                        {
                            Id = 25,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(3521),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-56.150231 -34.916723)"),
                            Name = "Cineworld Houston",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(3522)
                        });
                });

            modelBuilder.Entity("WebAPI_tutorial_peliculas.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(301),
                            Name = "Aventura",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(330)
                        },
                        new
                        {
                            Id = 2,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(330),
                            Name = "Animación",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(331)
                        },
                        new
                        {
                            Id = 3,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(331),
                            Name = "Suspenso",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(332)
                        },
                        new
                        {
                            Id = 4,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(332),
                            Name = "Romance",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(333)
                        },
                        new
                        {
                            Id = 5,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(334),
                            Name = "Terror",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(334)
                        },
                        new
                        {
                            Id = 6,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(335),
                            Name = "Comedia",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(335)
                        },
                        new
                        {
                            Id = 7,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(336),
                            Name = "Sci-fi",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(337)
                        },
                        new
                        {
                            Id = 8,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(338),
                            Name = "Documental",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(338)
                        });
                });

            modelBuilder.Entity("WebAPI_tutorial_peliculas.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OnCinema")
                        .HasColumnType("bit");

                    b.Property<string>("PosterURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Premiere")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Trailer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1057),
                            Description = "Un viaje interestelar en busca de un nuevo hogar para la humanidad.",
                            OnCinema = true,
                            PosterURL = "https://m.media-amazon.com/images/I/A1JVqNMI7UL._AC_UF894,1000_QL80_.jpg",
                            Premiere = new DateTime(2014, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Interstellar",
                            Trailer = "https://www.youtube.com/watch?v=2LqzF5WauAw",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1064)
                        },
                        new
                        {
                            Id = 2,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1068),
                            Description = "La vida de un hombre es un reality show televisado las 24 horas.",
                            OnCinema = true,
                            PosterURL = "https://flxt.tmsimg.com/assets/p20974_p_v10_aq.jpg",
                            Premiere = new DateTime(1998, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Truman Show",
                            Trailer = "https://www.youtube.com/watch?v=dpDhYDiHxgU",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1068)
                        },
                        new
                        {
                            Id = 3,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1069),
                            Description = "Un adolescente viaja al pasado y al futuro en un DeLorean modificado.",
                            OnCinema = false,
                            PosterURL = "https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/Back_to_the_Future_Part_II.jpg/220px-Back_to_the_Future_Part_II.jpg",
                            Premiere = new DateTime(1989, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Back to the future",
                            Trailer = "https://www.youtube.com/watch?v=qvsgGtivCgs",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1070)
                        },
                        new
                        {
                            Id = 4,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1072),
                            Description = "Agentes secretos protegen a la Tierra de amenazas extraterrestres.",
                            OnCinema = false,
                            PosterURL = "https://upload.wikimedia.org/wikipedia/en/f/fb/Men_in_Black_Poster.jpg",
                            Premiere = new DateTime(1997, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Men in black",
                            Trailer = "https://www.youtube.com/watch?v=UxUTTrU6PA4",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1072)
                        },
                        new
                        {
                            Id = 5,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1073),
                            Description = "Un payaso asesino siembra el terror en la noche de Halloween.",
                            OnCinema = true,
                            PosterURL = "https://m.media-amazon.com/images/M/MV5BYmMxNzA0OTUtOTJiOS00NTc4LWJmNTItMGM3OWE0N2Y0NjhjXkEyXkFqcGdeQXVyMTg5NjU4NjE@._V1_FMjpg_UX1000_.jpg",
                            Premiere = new DateTime(2018, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Terrifier",
                            Trailer = "https://www.youtube.com/watch?v=fN5j1MtGO2Q",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1074)
                        },
                        new
                        {
                            Id = 6,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1075),
                            Description = "Un grupo de amigos se ve atrapado en un festival pagano en Suecia.",
                            OnCinema = true,
                            PosterURL = "https://grandillusioncinema.org/wp-content/uploads/2023/06/midsommar.jpg",
                            Premiere = new DateTime(2019, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Midsommar",
                            Trailer = "https://www.youtube.com/watch?v=1Vnghdsjmd0",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1075)
                        },
                        new
                        {
                            Id = 7,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1077),
                            Description = "Una familia del siglo XVII enfrenta fuerzas sobrenaturales en su granja.",
                            OnCinema = true,
                            PosterURL = "https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/The_Witch_poster.png/220px-The_Witch_poster.png",
                            Premiere = new DateTime(2023, 6, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1078),
                            Title = "The Witch",
                            Trailer = "https://www.youtube.com/watch?v=iQXmlf3Sefg",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1077)
                        },
                        new
                        {
                            Id = 8,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1086),
                            Description = "Dos investigadores paranormales toman un caso de posesión demoníaca.",
                            OnCinema = true,
                            PosterURL = "https://upload.wikimedia.org/wikipedia/en/thumb/9/9b/The_Conjuring_The_Devil_Made_Me_Do_It_poster.jpeg/220px-The_Conjuring_The_Devil_Made_Me_Do_It_poster.jpeg",
                            Premiere = new DateTime(2023, 7, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1087),
                            Title = "The Conjuring: The Devil Made Me Do It",
                            Trailer = "https://www.youtube.com/watch?v=YDGw1MTEe9k",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1086)
                        },
                        new
                        {
                            Id = 9,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1089),
                            Description = "Una familia debe sobrevivir en un mundo invadido por criaturas que cazan por el sonido.",
                            OnCinema = true,
                            PosterURL = "https://upload.wikimedia.org/wikipedia/en/thumb/a/a0/A_Quiet_Place_Part_II.jpeg/220px-A_Quiet_Place_Part_II.jpeg",
                            Premiere = new DateTime(2023, 5, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1090),
                            Title = "A Quiet Place Part II",
                            Trailer = "https://www.youtube.com/watch?v=XEMwSdne6UE",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1089)
                        },
                        new
                        {
                            Id = 11,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1091),
                            Description = "Un programador descubre que la realidad es una simulación creada por máquinas inteligentes.",
                            OnCinema = false,
                            PosterURL = "https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg",
                            Premiere = new DateTime(2003, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1092),
                            Title = "The Matrix",
                            Trailer = "https://www.youtube.com/watch?v=m8e-FF8MsqU",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1091)
                        },
                        new
                        {
                            Id = 12,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1094),
                            Description = "Un cazador de replicantes debe encontrar y 'retirar' a cuatro androides que han regresado a la Tierra.",
                            OnCinema = false,
                            PosterURL = "https://upload.wikimedia.org/wikipedia/en/5/53/Blade_Runner_poster.jpg",
                            Premiere = new DateTime(1993, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1095),
                            Title = "Blade Runner",
                            Trailer = "https://www.youtube.com/watch?v=eogpIG53Cis",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1095)
                        },
                        new
                        {
                            Id = 13,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1096),
                            Description = "Un ladrón de sueños toma un último trabajo para implantar una idea en la mente de un ejecutivo.",
                            OnCinema = false,
                            PosterURL = "https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg",
                            Premiere = new DateTime(2013, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1098),
                            Title = "Inception",
                            Trailer = "https://www.youtube.com/watch?v=YoHD9XEInc0",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1097)
                        },
                        new
                        {
                            Id = 14,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1099),
                            Description = "Un androide asesino viaja al pasado para eliminar a la madre del líder de la resistencia humana.",
                            OnCinema = false,
                            PosterURL = "https://upload.wikimedia.org/wikipedia/en/7/70/Terminator1984movieposter.jpg",
                            Premiere = new DateTime(1983, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1100),
                            Title = "The Terminator",
                            Trailer = "https://www.youtube.com/watch?v=k64P4l2Wmeg",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1099)
                        },
                        new
                        {
                            Id = 15,
                            Creation = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1101),
                            Description = "Un joven granjero se une a la rebelión para derrotar al malévolo Imperio Galáctico.",
                            OnCinema = false,
                            PosterURL = "https://upload.wikimedia.org/wikipedia/en/8/87/StarWarsMoviePoster1977.jpg",
                            Premiere = new DateTime(1983, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1102),
                            Title = "Star Wars: Episode IV - A New Hope",
                            Trailer = "https://www.youtube.com/watch?v=vZ734NWnAHA",
                            Update = new DateTime(2023, 9, 8, 21, 54, 40, 440, DateTimeKind.Local).AddTicks(1101)
                        });
                });

            modelBuilder.Entity("WebAPI_tutorial_peliculas.Models.MovieCinema", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "CinemaId");

                    b.HasIndex("CinemaId");

                    b.ToTable("MovieCinema");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CinemaId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            CinemaId = 2
                        },
                        new
                        {
                            MovieId = 2,
                            CinemaId = 1
                        },
                        new
                        {
                            MovieId = 3,
                            CinemaId = 2
                        },
                        new
                        {
                            MovieId = 3,
                            CinemaId = 3
                        },
                        new
                        {
                            MovieId = 4,
                            CinemaId = 4
                        },
                        new
                        {
                            MovieId = 5,
                            CinemaId = 5
                        },
                        new
                        {
                            MovieId = 5,
                            CinemaId = 1
                        });
                });

            modelBuilder.Entity("WebAPI_tutorial_peliculas.Models.MovieGenre", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenre");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 2,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 2,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 3,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 4,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 4,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 5,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 5,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 6,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 8,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 9,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 11,
                            GenreId = 7
                        },
                        new
                        {
                            MovieId = 12,
                            GenreId = 7
                        },
                        new
                        {
                            MovieId = 13,
                            GenreId = 7
                        },
                        new
                        {
                            MovieId = 14,
                            GenreId = 7
                        },
                        new
                        {
                            MovieId = 15,
                            GenreId = 7
                        },
                        new
                        {
                            MovieId = 8,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 9,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 11,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 12,
                            GenreId = 5
                        });
                });

            modelBuilder.Entity("WebAPI_tutorial_peliculas.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("WebAPI_tutorial_peliculas.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebAPI_tutorial_peliculas.Models.ActorMovie", b =>
                {
                    b.HasOne("WebAPI_tutorial_peliculas.Models.Actor", "Actor")
                        .WithMany("ActorMovieList")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI_tutorial_peliculas.Models.Movie", "Movie")
                        .WithMany("ActorMovieList")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("WebAPI_tutorial_peliculas.Models.MovieCinema", b =>
                {
                    b.HasOne("WebAPI_tutorial_peliculas.Models.Cinema", "Cinema")
                        .WithMany("MovieCinemaList")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI_tutorial_peliculas.Models.Movie", "Movie")
                        .WithMany("MovieCinemaList")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("WebAPI_tutorial_peliculas.Models.MovieGenre", b =>
                {
                    b.HasOne("WebAPI_tutorial_peliculas.Models.Genre", "Genre")
                        .WithMany("MovieGenreList")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI_tutorial_peliculas.Models.Movie", "Movie")
                        .WithMany("MovieGenreList")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("WebAPI_tutorial_peliculas.Models.Rating", b =>
                {
                    b.HasOne("WebAPI_tutorial_peliculas.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebAPI_tutorial_peliculas.Models.Review", b =>
                {
                    b.HasOne("WebAPI_tutorial_peliculas.Models.Movie", "Movie")
                        .WithMany("ReviewList")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebAPI_tutorial_peliculas.Models.Actor", b =>
                {
                    b.Navigation("ActorMovieList");
                });

            modelBuilder.Entity("WebAPI_tutorial_peliculas.Models.Cinema", b =>
                {
                    b.Navigation("MovieCinemaList");
                });

            modelBuilder.Entity("WebAPI_tutorial_peliculas.Models.Genre", b =>
                {
                    b.Navigation("MovieGenreList");
                });

            modelBuilder.Entity("WebAPI_tutorial_peliculas.Models.Movie", b =>
                {
                    b.Navigation("ActorMovieList");

                    b.Navigation("MovieCinemaList");

                    b.Navigation("MovieGenreList");

                    b.Navigation("ReviewList");
                });
#pragma warning restore 612, 618
        }
    }
}
